version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0

workflows:
  ci:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
          source-dir: src/golang
          destination-orb-path: golang.yml
          workspace-path: golang.yml
      - orb-tools/pack:
          requires:
            - orb-tools/lint
          source-dir: src/snyk
          destination-orb-path: snyk.yml
          workspace-path: snyk.yml
