version: 2

jobs:
  validate:
    docker:
      - image: circleci/buildpack-deps:latest
    steps:
      - run:
          name: Get Circle CI CLI
          command: |
            mkdir $HOME/bin &&
            # Eww :-(
            curl -fLSs https://circle.ci/cli | DESTDIR=$HOME/bin bash &&
            echo 'export PATH=$HOME/bin:$PATH' >> $BASH_ENV
      - checkout
      - run:
          name: Validate ORBS
          command: |
            circleci --help &&
            circleci version &&
            for orb in $(ls ./src); do
              make ORB=${orb} validate
            done

workflows:
  version: 2
  ci:
    jobs:
      - validate
