version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.2

workflows:
  ci:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
          source-dir: src/install-sfdx
          destination-orb-path: install-sfdx.yml
          workspace-path: install-sfdx.yml
      - orb-tools/pack:
          requires:
            - orb-tools/lint
          source-dir: src/golang
          destination-orb-path: golang.yml
          workspace-path: golang.yml
      - orb-tools/pack:
          requires:
            - orb-tools/lint
          source-dir: src/sfdx-auth
          destination-orb-path: sfdx-auth.yml
          workspace-path: sfdx-auth.yml
      - orb-tools/pack:
          requires:
            - orb-tools/lint
          source-dir: src/snyk
          destination-orb-path: snyk.yml
          workspace-path: snyk.yml
      - orb-tools/pack:
          requires:
            - orb-tools/lint
          source-dir: src/terraform-for-test
          destination-orb-path: terraform-for-test.yml
          workspace-path: terraform-for-test.yml
